#!/usr/bin/env bash
# Numbers from 1 to 100/displays "FizzBuzz"
a=1
while [ $a -le 100 ]
do
	echo "$a"
	if [[ $((a%3)) = 0 ]];
	then 
		printf "Fizz\n"
	elif [[ $((a%5)) = 0 ]];
	then
	        echo Buzz
	fi
	case "$a" in 
		        "15") echo FizzBuzz;;
			"30") echo FizzBuzz;;
	         	"45") echo FizzBuzz;;
			"60") echo FizzBuzz;;
			"75") echo FizzBuzz;;
			"90") echo FizzBuzz;;
		esac
	((a++))
done
