#!/usr/bin/env bash
# Numbers from 1 to 100/displays "FizzBuzz"
a=1
while [ $a -le 100 ]
do
	
	if [[ $((a%3)) = 0 ]] && [[ $((a%5)) = 0 ]];
	then 
		echo FizzBuzz
	
	elif [[ $((a%5)) = 0 ]] && [[ $((a%3)) != 0 ]];
	then
	        echo Buzz
        
	elif [[ $((a%3)) = 0 ]] && [[ $((a%5)) != 0 ]];
	then
		echo Fizz
	else 
		echo $a
	fi
	((a++))

done
