#!/usr/bin/env bash
# Numbers from 1 to 100/displays "FizzBuzz"
a=1
while [ $a -eq 100 ]
do
	echo $a
	case $a in
		"$a*3" ) echo 'Fizz';;
		"$a*5" ) echo 'Buzz';;
		"$a*15" ) echo 'FizzBuzz';;
	esac
done
