#!/usr/bin/env bash
# Display the content of the file /etc/passwd, using while loop + IFS

File="/etc/passwd"
while IFS=: read -r username group_id homedir commandshell userid passwd useridinfo
do
	printf "The user %s is part of the %f gang, lives in %s and rides %s. %i's place is protected by the passcode %s, more info about the user here: %s" $username $group_id $homedir $commandshell $userid $passwd $useridinfo
done < $File
