#!/usr/bin/env bash
# Use "while loop" & "if statement" for display Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
a=1
while [ $a -le 10 ]
do
echo Best School
((a++))
if [[ $a = 10 ]]; then
	echo Hi
fi
done
