#!/usr/bin/env bash
# Displays numbers from 1 to 20, mark 'bad luck from China' under 4th iteration, 'bad luck from Japan' under 9th iteration, and 'bad luck from Italy' under 17th. (while loop with case statement)
a=1
while [ $a -lt 20 ]
do
	echo "$a"
	(( a += 1 ))
		case "$a" in
		"5" ) echo 'bad luck from China';;
		"10" ) echo 'bad luck from Japan';;
		"18" ) echo 'bad luck from Italy';;
		esac
	done
