#!/usr/bin/env bash
# Display the time for 12 hrs (0-12) and 59 mins (1-59) by using while loop (show first 70 lines only)
a=0
while [ $a -le 12 ]
do echo "Hour: $a"
	b=1
	while [ $b -le 59 ]
	do printf "%i\n" $b
		((b++))
	done
	((a++))
done
