#!/usr/bin/env bash
# A script that gives the information about "school" file by using if and else.
a=school
if [[ -a $a ]];
then 
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [[ -s $a ]];
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [[ -f $a ]];
then
	echo "school is a regular file"
fi
