#!/usr/bin/env bash
# A script: 
# create the file "/var/run/myscript.pid containing its PID
# display "To infinity and beyond" indefinitely 
# display " I hate the kill command" when receiving a SIGTERM signal 
# display "Y U no love me?!" when receiving a SIGINT signal 
# deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo '$$' > /var/run/myscript.pid

trap "echo I hate the kill command" SIGTERM  "echo Y U no love me?!" SIGINT 
while :
do
	echo "To infinity and beyond"
done

kill-9 > '/var/run/myscript.pid'
