#!/usr/bin/env bash
# A script: 
# create the file "/var/run/myscript.pid containing its PID
# display "To infinity and beyond" indefinitely 
# display " I hate the kill command" when receiving a SIGTERM signal 
# display "Y U no love me?!" when receiving a SIGINT signal 
# deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo '$$' > /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT 
trap 'rm /var/run/myscript.pid; exit' SIGQUIT
while :
do
	echo "To infinity and beyond"
done
