#!/usr/bin/env bash
# Programe that manages "manage_my_process", require start, stop, restart.
if [ "$1" = "start" ]
then
	echo "manage_my_process started" 
./manage_my_process &
echo $$ > /var/run/my_process.pid

elif [ "$1" = "stop" ]
then
	echo "manage_my_process stopped"
	pkill -9 -f manage_my_process
       # rm /var/run/my_process.pid

elif [ "$1" = "restart" ]
then
	echo "manage_my_process restarted"

# rm /var/run/my_process.pid

else echo "Usage: manage_my_process {start|stop|restart}"
fi
