#!/usr/bin/env bash
# Programe that manages "manage_my_process", require start, stop, restart.
pid=/var/run/my_process.pid
if [ "$1" = "start" ]
then
	echo "manage_my_process started" 
	sudo ./manage_my_process &
       	echo "$!" > "$pid"

elif [ "$1" = "stop" ]
then
	sudo kill "$(cat $pid)" &&
       	rm -f "$pid"
	echo "manage_my_process stopped"

elif [ "$1" = "restart" ]
then
	sudo kill "$(cat $pid)" &&
       	rm -f "$pid"
	sudo ./manage_my_process & echo "$!" > "$pid"
	echo "manage_my_process restarted"

else 
	echo "Usage: manage_my_process {start|stop|restart}"
fi
