#!/usr/bin/env bash
# Display -To infinity and beyond indefinitely- with a sleep 2 in between each iteration- 'I am invincible!!!' when receiving a SIGTERM signal.
trap "I am invicible!!!" SIGTERM

while true
do
     echo "To infinity and beyond"
     sleep 2
     done
